webProfesional/blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed
#crea tus urls de la app

app_name= 'blog'
urlpatterns = [
	path('',  views.post_list, name="post_list"),
	path('<int:post_id>/<slug:post_slug>/',views.post_detail, name='post_detail'),
	path('<int:post_id>/<slug:post_slug>/share/',views.post_share, name='post_share'),
	path('category/<int:category_id>/<slug:post_slug>/', views.category, name="category"),

	path('reply/<int:comment_id>/',views.commet_reply, name='commet_reply'),

	path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),

	path('feed/', LatestPostsFeed(), name='post_feed'),
	path('search/', views.post_search, name='post_search'),



]

webProfesional/core/urls.py
from django.urls import path
from . import views

#crea tus urls de la app

app_name= 'core'
urlpatterns = [
	path('', views.home, name="home"),

]

webProfesional/webProfesional/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
'posts': PostSitemap,
}




urlpatterns = [
    path('', include('core.urls')),
    path('blog/', include('blog.urls')),
    path('about/', include('about.urls')),
    path('contact/', include('contact.urls')),

    #admin
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('grappelli/', include('grappelli.urls')), # grappelli URLS
    path('admin/', admin.site.urls),

    #Sitemaps
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap')
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

webProfesional/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from ckeditor_uploader.fields import RichTextUploadingField
from django.urls import reverse
from taggit.managers import TaggableManager
from datetime import date
from colorfield.fields import ColorField
hoy = date.today()


class Category(models.Model):
    name = models.CharField(max_length=100,
        verbose_name="Nombre")
    created = models.DateTimeField(auto_now_add=True,
        verbose_name="Fecha de creación")
    content = RichTextUploadingField(verbose_name= "Contenido",  null=True, blank=True)

    image = models.ImageField(upload_to="category", null=True, blank=True,
        verbose_name="Imagen")

    updated = models.DateTimeField(auto_now=True,
        verbose_name="Fecha de edición")

    slug = models.SlugField(max_length=250)

    class Meta:
        unique_together = ('slug', )
        verbose_name = "Categoría"
        verbose_name_plural = "Categorías"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog:category',
                       args=[self.id,
                           self.slug])





# Create your models here.
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,self).get_queryset()\
            .filter(status='published')

class Post(models.Model):
    STATUS_CHOICES = (
    ('draft', 'Draft'),
    ('published', 'Published'),
    )
    title = models.CharField(max_length=250, verbose_name='Titulo')
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    portada = models.ImageField(verbose_name='Adjunta una Imagen', upload_to='blog', blank=True, null=True)
    author = models.ForeignKey(User,on_delete=models.CASCADE,related_name='blog_posts')
    body = RichTextUploadingField(verbose_name='Contenido')
    publish = models.DateTimeField(default=timezone.now)
    tags = TaggableManager()
    categories = models.ForeignKey(Category,on_delete=models.CASCADE,related_name='blog_category')
    objects = models.Manager()  # The default manager.
    published = PublishedManager()  # Nuestro modelo personalizado PublishedManager
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,choices=STATUS_CHOICES,default='draft')
    visit = models.IntegerField(verbose_name='cantidad de visitas', default=0)

    #si es sliders
    sliders = models.BooleanField(default=False, blank=True, null=True)
    color_titulo = ColorField(verbose_name="Selecciona Color del Titulo", blank=True, null=True,default='#FFFFFF')
    color_subtitulo = ColorField(verbose_name="Selecciona Color del Subtitulo", blank=True, null=True,default='#FFFFFF')
    
    class Meta:
        verbose_name = "Publicación"
        verbose_name_plural = "Publicaciones"
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.id,
                           self.slug])


    def numeroTicket(self):
        return (str(self.id).zfill(8))

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE,related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        verbose_name = "Comentario"
        verbose_name_plural = "Comentarios"
        ordering = ('created',)

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'



class Reply(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE,related_name='repuesta')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        verbose_name = "Respuesta"
        verbose_name_plural = "Respuestas"
        ordering = ('created',)

    def __str__(self):
        return f'Comment by {self.name} on {self.comment}'

webProfesional/blog/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=100,label='Nombre',min_length=3,required=True,widget=forms.TextInput(attrs={'placeholder': 'Escriba su nombre...','class': 'form-control my-2'}))
    email = forms.EmailField(max_length=200,label='Email',min_length=3,required=True,widget=forms.TextInput(attrs={'placeholder': 'Escriba su Email...','class': 'form-control my-2'}))
    to = forms.EmailField(max_length=200,label='Para:',min_length=3,required=True,widget=forms.TextInput(attrs={'placeholder': 'Escriba el Email a compartir..','class': 'form-control my-2'}))
    comments = forms.CharField(max_length=1000,label='Comentario',min_length=3,required=True,widget=forms.Textarea(attrs={'placeholder': 'Escriba uncomentario...','class': 'form-control mb-3 ml-3 my-2', 'rows':3}))


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

        widgets = {
            'name': forms.TextInput(
                attrs={'class': 'form-control', 'required': 'True', 'placeholder': 'Escriba su nombre...'}),
            'email': forms.TextInput(
                attrs={'class': 'form-control', 'required': 'True', 'placeholder': 'Escriba su email...' }),
             'body': forms.Textarea(
                attrs={'class': 'form-control mb-3 mr-3', 'required': 'True', 'placeholder': 'Escriba su comentario...', 'rows':'5' }),
        }
        labels = {
            'name': 'Nombre',
            'email': 'Email',
            'body': 'Comentario',
        }

class ReplyCommentPostForm(forms.Form):
    name = forms.CharField(max_length=100,label='Nombre',min_length=3,required=True,widget=forms.TextInput(attrs={'placeholder': 'Escriba su nombre...','class': 'form-control my-2'}))
    email = forms.EmailField(max_length=200,label='Email',min_length=3,required=True,widget=forms.TextInput(attrs={'placeholder': 'Escriba su Email...','class': 'form-control my-2'}))
    body = forms.CharField(max_length=1000,label='Body',min_length=3,required=True,widget=forms.Textarea(attrs={'placeholder': 'Escriba su respuesta...','class': 'form-control mb-3 ml-3 my-2', 'rows':3}))



class SearchForm(forms.Form):
    query = forms.CharField(max_length=100,label='',min_length=3,required=True,widget=forms.TextInput(attrs={'placeholder': 'Search..','class': 'form-control','type': 'text'}))

webProfesional/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from .models import Post, Comment, Category, Reply
from django.views.generic.list import ListView
from django.db.models import Q
from .forms import EmailPostForm, CommentForm, SearchForm, ReplyCommentPostForm
from django.core.mail import send_mail
from django.contrib import messages
from django.db.models import Count
from django.views.generic.detail import DetailView
from django.views.generic.list import MultipleObjectMixin
from taggit.models import Tag
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from django.core.paginator import Paginator, EmptyPage,PageNotAnInteger
from contact.models import Contact
# Create your views here.


#Muestra el Post detallado
def post_detail(request, post_id, post_slug):
    post = get_object_or_404(Post, slug=post_slug,
                             id=post_id)

    # Visitas
    post.visit = post.visit + 1
    post.save()

    mas_visitados = Post.published.order_by('-visit')[:5]

    comments = post.comments.filter(active=True)
    new_comment = None

    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
        # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()

    else:
        comment_form = CommentForm()


    # List of similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]





    contex={
        'post': post,
        'comments': comments,
        'new_comment': new_comment,
        'comment_form': comment_form,
        'similar_posts': similar_posts,
        'mas_visitados': mas_visitados,

    }
    return render(request,'blog/detail_adaptado.html', contex)

#Comparte el post desde un formulario
def post_share(request, post_id, post_slug):
    post = get_object_or_404(Post, id=post_id, slug=post_slug, status='published')
    sent = False
    form = EmailPostForm()
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            # ... send email
            post_url = request.build_absolute_uri(
                post.get_absolute_url())
            subject = f"{cd['name']} te recomienda leer " \
                      f"{post.title}"
            message = f"Desde  mi Blog te enviamos  {post.title} at {post_url}\n\n" \
                      f"De parte de :{cd['name']}\n\n Y mis comentarios son: {cd['comments']}"
            send_mail(subject, message, 'rocoweb@outlook.com',
                      [cd['to']])
            sent = True
            Contact.objects.create(
                name='Shared ' + cd['name'],
                email=cd['email'],
                subject=cd['to'],
                content=cd['comments'])

            #messages.success(request, "Mensaje enviado Correctamente.")
        else:
            form = EmailPostForm()
    return render(request, 'blog/share.html', {'post': post,
                                                    'form': form,
                                                    'sent': sent,
                                                    },)

#Tampoco funcional
def post_search(request):
    form = SearchForm()
    query = None
    results = []

    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            search_vector = SearchVector('title', weight='A') + SearchVector('body', weight='B')
            search_query = SearchQuery(query)
            results = Post.published.annotate(
                search=search_vector,
                rank=SearchRank(search_vector, search_query)
            ).filter(rank__gte=0.3).order_by('-rank')

    return render(request,'blog/search.html',{'form': form,
                                                       'query': query,
                                                       'results': results})

#vista los post list por categoria
def category(request, category_id, post_slug, tag_slug=None):
    category = get_object_or_404(Category, id=category_id, slug=post_slug)
    object_list = Post.published.filter(categories__id=category_id)
    mas_visitados = Post.published.order_by('-visit')[:5]
    # Show most common tags
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])
    common_tags = Post.tags.most_common()[:15]
    paginator = Paginator(object_list, 5)  # 3 posts in each page



    page_num  = request.GET.get('page',1)
    try:
        page_obj = paginator.page(page_num )
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        page_obj = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        page_obj = paginator.page(paginator.num_pages)

    queryset = request.GET.get('search')
    if queryset:
        page_obj = Post.published.filter(categories__id=category_id).filter(
            Q(title__icontains=queryset) |
            Q(body__icontains=queryset)
        ).distinct()

    return render(request, "blog/category.html", {'category':category,
                                                  'object_list':object_list,
                                                  'page_obj': page_obj,
                                                  'mas_visitados': mas_visitados,
                                                  'common_tags': common_tags,
                                                  'tag': tag,
                                                  })

#Muestra los post list genericos
def post_list(request ,tag_slug=None):
    object_list = Post.published.all()
    common_tags = Post.tags.most_common()[:20]
    mas_visitados = Post.published.order_by('-visit')[:5]



    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])


    paginator = Paginator(object_list, 5)  # 3 posts in each page

    page_num = request.GET.get('page', 1)
    try:
        page_obj = paginator.page(page_num)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        page_obj = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        page_obj = paginator.page(paginator.num_pages)

    queryset = request.GET.get('search')
    if queryset:
        page_obj = Post.published.filter(
            Q(title__icontains=queryset) |
            Q(body__icontains=queryset)
        ).distinct()

    return render(request, "blog/blog_list.html", {
                                                    'object_list': object_list,
                                                    'page_obj': page_obj,
                                                    'common_tags': common_tags,
                                                    'mas_visitados': mas_visitados,
                                                    'tag': tag,
                                                  })

#Comparte el post desde un formulario
def commet_reply(request, comment_id):
    comment = get_object_or_404(Comment,id=comment_id)
    reply = None


    if request.method == 'POST':
        reply_form = ReplyCommentPostForm(data=request.POST)
        if reply_form.is_valid():
            cd = reply_form.cleaned_data
            reply = Reply.objects.create(
                name=cd['name'],
                email=cd['email'],
                body=cd['body'],
                comment_id =comment_id)
            return redirect(reverse('blog:post_list') + "?ok")
    else:
        reply_form = ReplyCommentPostForm()

    context = {
        'reply': reply,
        'reply_form': reply_form,

    }
    return render(request, 'blog/reply_comment.html', context)

webProfesional/blog/templates/blog/blog_list.html
{% extends 'core/base.html' %}
{% block title %}Principal{% endblock %}
{% load static %}
{% load blog_tags %}
{% block content %}

    <!-- ======= BLOG Section ======= -->
     <section>
      <div class="container">
        <div class="row">

          <div class="col-md-9" data-aos="fade-up">
            <h3 class="category-title text-center">Todas las publicaciones. </h3>
            {% for post in page_obj %}
            <div class="d-md-flex post-entry-2 half">
              <a href="{{post.get_absolute_url}}" class="me-4 thumbnail">
                {% if post.portada %}
                <img src="{{post.portada.url}}" alt="" class="img-fluid">
                {% endif%}
              </a>
              <div>
                <div class="post-meta"><span class="date">{{ post.categories.name }}</span> <span class="mx-1">&bullet;</span> <span>{{post.created}}</span></div>
                <h3><a href="{{post.get_absolute_url}}">{{post.title}}</a></h3>
                <p>{{post.body|safe|truncatechars:200}}</p>
                <div class="d-flex align-items-center author">
                  <div class="photo"><img src="assets/img/person-2.jpg" alt="" class="img-fluid"></div>
                  <div class="name">
                    <h3 class="m-0 p-0">{{post.author.name}}</h3>
                  </div>

                </div>
              </div>
            </div>

             {% endfor %}
            {% include 'includes/pagination.html' %}

          </div>

          <div class="col-md-3">
            <!-- ======= Sidebar ======= -->
            <div class="aside-block">

              <ul class="nav nav-pills custom-tab-nav mb-4" id="pills-tab" role="tablist">
                <li class="nav-item" role="presentation">
                  <button class="nav-link active" id="pills-popular-tab" data-bs-toggle="pill" data-bs-target="#pills-popular" type="button" role="tab" aria-controls="pills-popular" aria-selected="true">Mas Comentados</button>
                </li>
                <li class="nav-item" role="presentation">
                  <button class="nav-link" id="pills-trending-tab" data-bs-toggle="pill" data-bs-target="#pills-trending" type="button" role="tab" aria-controls="pills-trending" aria-selected="false">Trending</button>
                </li>
                <li class="nav-item" role="presentation">
                  <button class="nav-link" id="pills-latest-tab" data-bs-toggle="pill" data-bs-target="#pills-latest" type="button" role="tab" aria-controls="pills-latest" aria-selected="false">Mas Recientes</button>
                </li>
              </ul>

              <div class="tab-content" id="pills-tabContent">

                <!-- Popular -->
                {% show_most_commented_posts 5 %}

                <!-- Trending -->

                <div class="tab-pane fade" id="pills-trending" role="tabpanel" aria-labelledby="pills-trending-tab">
                  {% for post in mas_visitados   %}
                  <div class="post-entry-1 border-bottom">
                    <div class="post-meta"><span class="date">{{post.categories.name}}</span> <span class="mx-1">&bullet;</span> <span>{{post.created}}</span></div>
                    <h2 class="mb-2"><a href="{{post.get_absolute_url}}">{{post.title}}</a></h2>
                    <span class="author mb-3 d-block">{{post.author}}</span>
                  </div>
                  {% endfor  %}


                </div> <!-- End Trending -->

                <!-- Latest -->
                {% show_latest_posts 5 %}

              </div>
            </div>

            <div class="aside-block">
              <h3 class="aside-title">Video</h3>
              <div class="video-post">
                <a href="https://www.youtube.com/watch?v=AiFfDjmd0jU" class="glightbox link-video">
                  <span class="bi-play-fill"></span>
                  <img src="assets/img/post-landscape-5.jpg" alt="" class="img-fluid">
                </a>
              </div>
            </div><!-- End Video -->

            <div class="aside-block">
              <h3 class="aside-title">Categorias</h3>
              <ul class="aside-links list-unstyled">
                {% for category in categories %}
                <li><a href="{{ category.get_absolute_url }}"><i class="bi bi-chevron-right"></i> {{category.name}}</a></li>
                {% endfor %}
              </ul>
            </div><!-- End Categories -->

            <div class="aside-block">
              <h3 class="aside-title">Etiquetas más Comunes</h3>
              <ul class="aside-tags list-unstyled">
                {% for tag in common_tags %}
                <li><a href="{% url 'blog:post_list_by_tag' tag.slug %}">{{tag}}</a></li>
                {% endfor %}
              </ul>
            </div><!-- End Tags -->
          </div>
        </div>
      </div>
    </section>

    <!-- End Culture Category Section -->




{% endblock %}

webProfesional/blog/templates/blog/detail_adaptado.html
{% extends 'core/base.html' %}
{% block title %}{{ post.title }}{% endblock %}
{% load static %}
{% load blog_tags %}
{% block content %}

    <section class="single-post-content">
      <div class="container">
        <div class="row">
          <div class="col-md-9 post-content" data-aos="fade-up">

            <!-- ======= Single Post Content ======= -->
            <div class="single-post">
              <div class="post-meta"><span class="date">{{post.categories.name}}</span> <span class="mx-1">&bullet;</span> <span>{{post.created}}</span></div>
              <h1 class="mb-5">{{post.title}}</h1>

              {% if post.portada %}
              <figure class="my-4">
                <img   src="{{post.portada.url}}" alt="" class="img-fluid">
              </figure>
              {% endif%}
                {{post.body|safe}}
                <div class="post-meta"><span class="date"><i class="bi bi-share-fill"></i></span> <span class="mx-1"></span> <a href="{% url 'blog:post_share'  post.id post.slug %}"><span>Compartir</span></a><span></span> <a href="{% url 'blog:post_feed' %}"><span>Subscribe to my RSS feed</span></a></div>

            </div><!-- End Single Post Content -->

             {% if comments %}
            <!-- ======= Comments ======= -->
                <div class="comments">
                  {% with comments.count as total_comments %}
                  <h5 class="comment-title py-4">Esta publicación tiene {{ total_comments }} comentario{{ total_comments|pluralize }}</h5>

                  {% endwith %}
                  {% for comment in comments %}
                  <div class="comment d-flex mb-4">                   
                     
                    <div class="flex-grow-1 ms-2 ms-sm-3">
                      <div class="comment-meta d-flex align-items-baseline">
                        <h6 class="me-2">{{ comment.name }}</h6>
                        <span class="text-muted">{{comment.created|date:'d-M-Y'}}{% if request.user.is_staff %}<a href="{% url 'blog:commet_reply' comment.id  %}" class="reply"><i class="bi bi-reply-fill m3"></i> Reply</a></span> {% endif %}
                      </div>
                      <div class="comment-body">
                       {{ comment.body|safe|linebreaks }}
                      </div>

                      {% if comment.repuesta.all %}
                      <!-- ======= Reply Commet ======= -->
                      <div class="comment-replies bg-light p-3 mt-3 rounded">
                         {% with comment.repuesta.all.count as total_reply %}
                        <h6 class="comment-replies-title mb-4 text-muted text-uppercase">{{ total_reply }} Respuesta{{ total_reply|pluralize }}</h6>
                        {% endwith %}
                        {% for respuesta in comment.repuesta.all %}
                        <div class="reply d-flex mb-4">
                          <div class="flex-grow-1 ms-2 ms-sm-3">
                              <div class="reply-meta d-flex align-items-baseline">
                                <h6 class="mb-0 me-2">{{respuesta.name}}</h6>
                                <span class="text-muted">{{respuesta.created}}</span>
                              </div>
                                <div class="reply-body">
                                  {{respuesta.body|safe}}
                                </div>
                          </div>
                        </div>
                         {% endfor %}
                      </div>
                      {% endif %}
                    </div>
                  </div> 
                   {% endfor %}               
                </div> <!-- End Comments -->
                

                      {% else %}
                <h5 class="comment-title py-4">Esta publicación aún no tiene comentarios... </h5>

             {% endif %}


            <!-- ======= Comments Form ======= -->
            <div class="row justify-content-center mt-5">

              <div class="col-lg-12">
                <h5 class="comment-title">Deja un comentario</h5>
                {% if new_comment %}
                <h2 style="color:green;">Tu comentario ha sido añadido correctamente...</h2>
                 {% endif %}
              <form method="post">
                 {% csrf_token %}
                    <div class="row">
                      <div class="col-lg-6 mb-3">
                       <input type="text"  name="name" class="form-control">
                      </div>
                      <div class="col-lg-6 mb-3">
                        <input type="text"  name="email" class="form-control">
                      </div>
                      <div class="col-12 mb-3">
                         {{comment_form.body}}
                      </div>
                      <div class="col-12">
                        <input type="submit" class="btn btn-primary" value="Post comment">
                      </div>
                    </div>
                  </div>
               </form>
            </div><!-- End Comments Form -->

          </div>
          <div class="col-md-3">
            <!-- ======= Sidebar ======= -->
            <div class="aside-block">

              <ul class="nav nav-pills custom-tab-nav mb-4" id="pills-tab" role="tablist">
                <li class="nav-item" role="presentation">
                  <button class="nav-link active" id="pills-popular-tab" data-bs-toggle="pill" data-bs-target="#pills-popular" type="button" role="tab" aria-controls="pills-popular" aria-selected="true">Popular</button>
                </li>
                <li class="nav-item" role="presentation">
                  <button class="nav-link" id="pills-trending-tab" data-bs-toggle="pill" data-bs-target="#pills-trending" type="button" role="tab" aria-controls="pills-trending" aria-selected="false">Trending</button>
                </li>
                <li class="nav-item" role="presentation">
                  <button class="nav-link" id="pills-latest-tab" data-bs-toggle="pill" data-bs-target="#pills-latest" type="button" role="tab" aria-controls="pills-latest" aria-selected="false">Latest</button>
                </li>
              </ul>

              <div class="tab-content" id="pills-tabContent">

                <!-- Popular -->
                 {% show_most_commented_posts 5 %}
                <!-- End Popular -->

                <!-- Trending -->

                <div class="tab-pane fade" id="pills-trending" role="tabpanel" aria-labelledby="pills-trending-tab">
                  {% for post in mas_visitados   %}
                  <div class="post-entry-1 border-bottom">
                    <div class="post-meta"><span class="date">{{post.categories.name}}</span> <span class="mx-1">&bullet;</span> <span>{{post.created}}</span></div>
                    <h2 class="mb-2"><a href="{{post.get_absolute_url}}">{{post.title}}</a></h2>
                    <span class="author mb-3 d-block">{{post.author}}</span>
                  </div>
                  {% endfor  %}


                </div> <!-- End Trending -->

                <!-- Latest -->
                {% show_latest_posts 5 %}
               <!-- End Latest -->

              </div>
            </div>

            <div class="aside-block">
              <h3 class="aside-title">Video</h3>
              <div class="video-post">
                <a href="https://www.youtube.com/watch?v=AiFfDjmd0jU" class="glightbox link-video">
                  <span class="bi-play-fill"></span>
                  <img src="assets/img/post-landscape-5.jpg" alt="" class="img-fluid">
                </a>
              </div>
            </div><!-- End Video -->

            <div class="aside-block">
              <h3 class="aside-title">Categories</h3>
              <ul class="aside-links list-unstyled">
                  {% for category in categories %}
                <li><a href="{{ category.get_absolute_url }}"><i class="bi bi-chevron-right"></i> {{category.name|capfirst}}</a></li>
                 {% endfor %}
                
              </ul>
            </div><!-- End Categories -->
             {% if post.tags.all %}
            <div class="aside-block">
              <h3 class="aside-title">Tags</h3>
              <ul class="aside-tags list-unstyled">
                 {% for tag in post.tags.all %}
                <li><a href="{% url 'blog:post_list_by_tag' tag.slug %}">{{tag}}</a></li>
                {% endfor %}
              </ul>
            </div><!-- End Tags -->
             {% endif %}

          </div>
        </div>
      </div>
    </section>

 {% endblock %}
 