webProfesional/about/urls.py
from django.urls import path
from . import views

#crea tus urls de la app

app_name= 'about'
urlpatterns = [
	path('', views.about, name="about"),


]

webProfesional/blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed
#crea tus urls de la app

app_name= 'blog'
urlpatterns = [
	path('',  views.post_list, name="post_list"),
	path('<int:post_id>/<slug:post_slug>/',views.post_detail, name='post_detail'),
	path('<int:post_id>/<slug:post_slug>/share/',views.post_share, name='post_share'),
	path('category/<int:category_id>/<slug:post_slug>/', views.category, name="category"),

	path('reply/<int:comment_id>/',views.commet_reply, name='commet_reply'),

	path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),

	path('feed/', LatestPostsFeed(), name='post_feed'),
	path('search/', views.post_search, name='post_search'),



]

webProfesional/contact/urls.py
from django.urls import path
from . import views




app_name= 'contact'

urlpatterns = [
	path('', views.contact, name="contact"),

]

webProfesional/core/urls.py
from django.urls import path
from . import views

#crea tus urls de la app

app_name= 'core'
urlpatterns = [
	path('', views.home, name="home"),

]

webProfesional/webProfesional/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
'posts': PostSitemap,
}




urlpatterns = [
    path('', include('core.urls')),
    path('blog/', include('blog.urls')),
    path('about/', include('about.urls')),
    path('contact/', include('contact.urls')),

    #admin
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('grappelli/', include('grappelli.urls')), # grappelli URLS
    path('admin/', admin.site.urls),

    #Sitemaps
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap')
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

webProfesional/core/views.py
from django.shortcuts import render, HttpResponse, get_object_or_404
from blog.models import Post
from django.db.models import Count
from django.db.models import Q



def home(request):
    posts = Post.published.filter(sliders=True)
    queryset = request.GET.get('search')
    if queryset:
        posts = Post.published.filter(
            Q(title__icontains=queryset) |
            Q(body__icontains=queryset)
        ).distinct()
    return render(request, "core/index.html", {'posts': posts})

webProfesional/core/templates/core/includes/categorias_lastests_portada.html
{% load blog_tags %}
    <div class="col-lg-4">
       {% show_latest_posts_categories 3 8 category.id as lastes_categories %}
      {% for post in lastes_categories %}
      <div class="post-entry-1 border-bottom">
        <div class="post-meta"><span class="date">{{post.category.name}}</span> <span class="mx-1">&bullet;</span> <span>{{post.created}}</span></div>
        <h2 class="mb-2"><a href="{{post.get_absolute_url}}">{{post.title}}</a></h2>
        <span class="author mb-3 d-block">{{post.author}}</span>
      </div>
        {% endfor %}
    </div>

webProfesional/core/templates/core/includes/footer.html
 {% load static %}
  {% load blog_tags %}
  <!-- ======= Footer ======= -->
  <footer id="footer" class="footer">

    <div class="footer-content">
      <div class="container">

        <div class="row g-5">
          <div class="col-lg-4">
            <h3 class="footer-heading">About RocoBlog</h3>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam ab, perspiciatis beatae autem deleniti voluptate nulla a dolores, exercitationem eveniet libero laudantium recusandae officiis qui aliquid blanditiis omnis quae. Explicabo?</p>
            <p><a href="{% url 'about:about' %}" class="footer-link-more">Learn More</a></p>
          </div>
          <div class="col-6 col-lg-2">
            <h3 class="footer-heading">Navigation</h3>
            <ul class="footer-links list-unstyled">
              <li><a href="{% url 'core:home' %}"><i class="bi bi-chevron-right"></i>Home</a></li>
              <li><a href="{% url 'blog:post_list' %}"><i class="bi bi-chevron-right"></i>Blog</a></li>
              <li><a href="{% url 'about:about' %}"><i class="bi bi-chevron-right"></i>Sobre Nosotros</a></li>
              <li><a href="{% url 'contact:contact' %}"><i class="bi bi-chevron-right"></i>Contacto</a></li>
            </ul>
          </div>
          <div class="col-6 col-lg-2">
            <h3 class="footer-heading">Categorias</h3>
            <ul class="footer-links list-unstyled">
              {% for category in categories %}
              <li><a href="{{ category.get_absolute_url }}"><i class="bi bi-chevron-right"></i>{{category.name|capfirst}}</a></li>
              {% endfor %}


            </ul>
          </div>

          <div class="col-lg-4">
            <h3 class="footer-heading">Recent Posts</h3>

            <ul class="footer-links footer-blog-entry list-unstyled">
            {% show_latest_posts_footer as latest %}
              {% for post in latest %}

              <li>
                <a href="{{post.get_absolute_url}}" class="d-flex align-items-center">

                  <div>
                    <div class="post-meta d-block"><span class="date">{{post.categories.name}}</span> <span class="mx-1">&bullet;</span> <span>{{post.created|date:"SHORT_DATETIME_FORMAT"}}</span></div>
                    <span>{{post.title}}</span>
                  </div>
                </a>
              </li>
               {% endfor %}

            </ul>

          </div>
        </div>
      </div>
    </div>

    <div class="footer-legal">
      <div class="container">

        <div class="row justify-content-between">





          <div class="col-md-12">
            <div class="social-links mb-3 mb-lg-0 text-center text-md-end">
              <a href="https://twitter.com/rocoblog01" class="twitter"><i class="bi bi-twitter"></i></a>
              <a href="https://www.facebook.com/profile.php?id=100085920625840" class="facebook"><i class="bi bi-facebook"></i></a>
              <a href="https://www.instagram.com/rocoblog01/" class="instagram"><i class="bi bi-instagram"></i></a>
              <a href="https://t.me/rocoblog" class="google-plus"><i class="bi bi-telegram"></i></a>

            </div>

          </div>

        </div>


    </div>

  </footer>

  <a href="#" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

webProfesional/core/templates/core/includes/header.html
{% load static %}

 <!-- ======= Header ======= -->
  <header id="header" class="header d-flex align-items-center fixed-top">
    <div class="container-fluid container-xl d-flex align-items-center justify-content-between">

      <a href="{% url 'core:home' %}" class="logo d-flex align-items-center">
        <!-- Uncomment the line below if you also wish to use an image logo -->
        <!-- <img src="assets/img/logo.png" alt=""> -->
        <h1>RocoBlog</h1>
      </a>

      <nav id="navbar" class="navbar">

        <ul>

          <li><a href="{% url 'core:home' %}">Home</a></li>
          <li><a href="{% url 'blog:post_list' %}">Blog</a></li>
          <li class="dropdown"><a href="#"> <span>Categories</span> <i class="bi bi-chevron-down dropdown-indicator"></a></i>
            <ul>
              {% for category in categories %}

              <li><a href="{{ category.get_absolute_url }}">{{category.name|capfirst}}</a></li>

             {% endfor %}
            </ul>
          </li>

          <li><a href="{% url 'about:about' %}">About</a></li>
          <li><a href="{% url 'contact:contact' %}">Contact</a></li>

        </ul>


      </nav><!-- .navbar -->

       <div class="position-relative">
        <a href="https://www.facebook.com/profile.php?id=100085920625840" class="mx-2"><span class="bi-facebook"></span></a>
        <a href="https://twitter.com/rocoblog01" class="mx-2"><span class="bi-twitter"></span></a>
        <a href="https://www.instagram.com/rocoblog01/" class="mx-2"><span class="bi-instagram"></span></a>
           <a href="https://t.me/rocoblog" class="mx-2"><span class="bi-telegram"></span></a>

        <a href="#" class="mx-2 js-search-open"><span class="bi-search"></span></a>
        <i class="bi bi-list mobile-nav-toggle"></i>

        <!-- ======= Search Form ======= -->
        <div class="search-form-wrap js-search-form-wrap">
          <form  role="search"  class="search-form" method="get">{% csrf_token %}
            <span class="icon bi-search"></span>
            <input type="text" placeholder="Search" class="form-control" name="search">
            <button class="btn js-search-close"><span class="bi-x"></span></button>
          </form>
        </div><!-- End Search Form -->

      </div>

    </div>

  </header><!-- End Header -->

webProfesional/core/templates/core/includes/messages.html
{% for message in messages %}
  <div class="container-fluid p-0" >
    <div class="alert {{ message.tags }} alert-dismissible" role="alert" >
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="True">&times;</span>
      </button>
      {{ message }}
    </div>
  </div>
{% endfor %}

webProfesional/core/templates/core/includes/primer_post.html
{% load blog_tags %}
<div class="col-lg-4">
      <div class="post-entry-1 lg">
        {% trending  0 1  as posts %}
        {% for post in posts %}
        <a href="single-post.html">
          {%  if post.portada %}

            <img src="{{post.portada.url}}" alt="" class="img-fluid"></a>
          {% else %}
              {% load static %}
            <img src="{% static 'core/assets/img/post-landscape-1.jpg' %}" alt="" class="img-fluid"></a>
          {% endif %}
        <div class="post-meta"><span class="date">{{post.category.name}}</span> <span class="mx-1">&bullet;</span> <span>{{post.created}}</span></div>
        <h2><a href="{{post.get_absolute_url}}">{{post.title}}</a></h2>
        <p class="mb-4 d-block">{{post.body|safe}}</p>

        <div class="d-flex align-items-center author">
          <div class="name">
            <h3 class="m-0 p-0">{{post.author}}</h3>
          </div>
        </div>
        {% endfor %}
      </div>

  </div>

webProfesional/core/templates/core/includes/primer_post_category.html
 {% load blog_tags %}

 {% show_latest_posts_categories 0 3 category.id as lastes_categories %}
  {% for post in lastes_categories %}
  <div class="post-entry-1">
    {% if post.portada  %}
    <a href="{{post.get_absolute_url}}"><img src="{{post.portada.url}}" alt="" class="img-fluid"></a>
     {% endif  %}
  <div class="post-meta"><span class="date">{{post.category.name}}</span> <span class="mx-1">&bullet;</span> <span>{{post.created}}</span></div>
    <h2><a href="{{post.get_absolute_url}}">{{post.title}}</a></h2>
    <p class="mb-4 d-block">{{post.body|safe|truncatechars:200}}</p>

    <div class="d-flex align-items-center author">
      <div class="name">
        <h3 class="m-0 p-0">{{post.author}}</h3>
      </div>
    </div>
  </div>
  {% endfor %}

webProfesional/core/templates/core/includes/slider.html
{% load static %}


<!-- ======= Hero Slider Section ======= -->
    <section id="hero-slider" class="hero-slider">
      <div class="container-md" data-aos="fade-in">
        <div class="row">
          <div class="col-12">
            <div class="swiper sliderFeaturedPosts">
              <div class="swiper-wrapper">
                 {% for post in posts %}
                <div class="swiper-slide">
                  <a href="{{post.get_absolute_url}}" class="img-bg d-flex align-items-end text-right" style="background-image: url('{{post.portada.url}}');">
                    <div class="img-bg-inner">
                      <h2 style="color:{{post.color_titulo}}" >{{post.title}}</h2>
                      <p style="color:{{post.color_subtitulo}}">{{post.body|truncatechars:200|safe }}</p>
                    </div>

                  </a>
                </div>
                  {% endfor %}
              </div>
              <div class="custom-swiper-button-next">
                <span class="bi-chevron-right"></span>
              </div>
              <div class="custom-swiper-button-prev">
                <span class="bi-chevron-left"></span>
              </div>
              <div class="swiper-pagination"></div>
            </div>
          </div>
        </div>
      </div>
    </section><!-- End Hero Slider Section -->

webProfesional/core/templates/core/includes/trending.html
{% load blog_tags %}
  <div class="col-lg-4">
        <div class="trending">
          <h3>Trending</h3>

            {% trending  1 7  as trendings %}
          <ul class="trending-post">

            {% for post in trendings %}
            <li>
              <a href="{{post.get_absolute_url}}">
                <span class="number">{{forloop.counter}}</span>
                <h3>{{post.title}}</h3>
                <span class="author">{{post.author}}</span>
              </a>
            </li>
             {% endfor %}

          </ul>
        </div>

</div>